[package]
name = "sizhe_chen_individual_project_2"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.17", features = ["derive"] }
csv = "1.1"
statrs = "0.16"
rusqlite = "0.29.0"
anyhow = "1.0"
